### ISSUE TITLE
Endianess?

### ISSUE THREAD

**Issue by zmip** [Manawyrm/SMAPHPConnect#1]
You write: "SMA uses a different endianess as usual". But is that the case, or is PHPmodbus faulty. 

https://github.com/krakorj/phpmodbus/issues/7

?

**Comment by Manawyrm** [comment]
I saw that you had already figured this out in more detail in the other thread...

But yeah, Modbus Endianess seems to be a bit non-standard at least. 
This endianess is the right one for SMA solar inverters, but I have never used it for anything other, so I can't judge which side is faulty.

**Comment by zmip** [comment]
Tobias, thanks for your comment. Your comment about "SMA uses a different endianness as usual" threw me off a bit. It turns out that the standard does not define endianness and (!) word order, so there's no "faulty" implementation, as I (and you?) assumed, just a lack of standardization.
